/**
 * 
 */
package test.cn.com.kc.blog.service;

import org.junit.Test;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.DefaultTransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import cn.com.kc.blog.bl.service.IBlogEntityService;
import cn.com.kc.blog.bl.service.IBlogUserService;
import cn.com.kc.blog.dao.service.IBlogUserDaoService;
import cn.com.kc.blog.pojo.BlogEntity;
import cn.com.kc.blog.pojo.BlogUser;

/**
 * @author chenjinlong2
 * 
 */
public class BlogUserServiceTester extends BootTester {

private static final String CREATE_TABLE_SQL = "create table test"
												+ "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
												+ "name varchar(100))";
private static final String DROP_TABLE_SQL = "drop table test";
private static final String INSERT_SQL = "insert into test(name,id) values(?,?)";
private static final String COUNT_SQL = "select count(*) from test";

public void testSaveUser() {
	try {
		final BlogUser user = new BlogUser();
		user.setShowName("show name");
		user.setUserName("KarlChan");
		user.setPassword("password");
		final IBlogUserService userService = (IBlogUserService) context
						.getBean(IBlogUserService.BEAN_NAME);
		userService.saveUser(user);
		final BlogUser user2 = new BlogUser();
		user2.setShowName("show name1");
		user2.setUserName("KarlChan2");
		user2.setPassword("password");
		userService.saveUser(user2);
		// userService.saveUser(user);
	} catch (Exception e) {
		e.printStackTrace();
	}

}

public void testTransactionTemplate() {
	TransactionTemplate template = new TransactionTemplate(jdbcTx);
}

public void testPlatformTransactionManager() {
	DefaultTransactionDefinition defDfin = new DefaultTransactionDefinition();
	defDfin
					.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);
	defDfin
					.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);
	TransactionStatus status = jdbcTx.getTransaction(defDfin);
	try {
		// jdbcTemplate.execute(CREATE_TABLE_SQL);
		jdbcTemplate.update(INSERT_SQL, "test", "1");
		jdbcTemplate.update(INSERT_SQL, "test", "2");
		if (true) {
			// throw new RuntimeException();
		}
		jdbcTx.commit(status);
	} catch (RuntimeException e) {
		jdbcTx.rollback(status);
		e.printStackTrace();
	}
}

public void testSaveNewEntity() {
	try {
		final BlogUser user = new BlogUser();
		user.setId(2224l);
		BlogEntity entity = new BlogEntity();
		entity.setUser(user);
		final IBlogEntityService entityService = (IBlogEntityService) context
						.getBean(IBlogEntityService.BEAN_NAME);
	} catch (Exception e) {
		e.printStackTrace();
	}
}

public void testDelUser() {
	try {
		final IBlogUserService userService = (IBlogUserService) context
						.getBean(IBlogUserService.BEAN_NAME);
		final BlogUser user = userService.getUser(2224l);
		userService.delUser(user);
	} catch (Exception e) {
		e.printStackTrace();
	}
}
}
